name: flutter_base
description: A new Flutter project with clean architecture.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  #ftp connect
  ftpconnect: ^2.0.5
  #path provider
  path_provider: ^2.1.1
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  #provider
  provider: ^6.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Network
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Utils
  logger: ^2.0.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  
  # Linting
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
